#!/bin/sh

CONFIG_FILE="/etc/config/advanced"

# Check if the configuration file already exists
if [ ! -f "$CONFIG_FILE" ]; then

    # Create the file
    touch "$CONFIG_FILE"
    
    # Add the 'defaults' section
    uci add advanced defaults

    # Save the changes
    uci commit advanced
fi

if ! uci show advanced.edcca >/dev/null 2>&1; then
    # Aggiunge la sezione 'edcca'
    uci add advanced edcca

    # Salva le modifiche
    uci commit advanced
fi

return 0
