include $(TOPDIR)/rules.mk

PKG_LICENSE:=GPL-3.0-only
PKG_MAINTAINER:=

LUCI_TITLE:=LuCI support for NordVPN Lite
LUCI_DESCRIPTION:=Provides a LuCI interface to configure NordVPN Lite.
LUCI_DEPENDS:=+luci-base +nordvpnlite
LUCI_PKGARCH:=all
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
