# See /LICENSE for more information.
# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI advanced app for WED HQoS
LUCI_DEPENDS:=+luci-base +mtkhnat_util
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0
PKG_MAINTAINER:=Andrea Pesaresi <andreapesaresi82@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
